### ISSUE TITLE
Next major roadmap

### ISSUE THREAD

**Issue by Soullivaneuh** [liip/LiipFunctionalTestBundle#338]
According to https://github.com/liip/LiipFunctionalTestBundle/pull/337#issuecomment-341079379, here is a roadmap for the next 2.0 major of this bundle:

- [x] Bump PHP support to 7.1 → #366
- [x] Introduce PHP7 type-hinting -> #379
- [x] Move to psr-4 new directory structure (`src` and `tests`) → #365
- [x] Bump PHPUnit support to v6 -> #379
- [x] Bump Symfony support to v3.4. As it's the next LTS, it would make sense
- [x] Bump nelmio/alice support to v3 => #268 and #337 
- [x] Bump Twig support to v2 -> #379
- [x] Bump jackalope/jackalope-doctrine-dbal support to v1.3 -> #379
- [x] Bump brianium/paratest to v1 -> #379
- [x] Check and bump other dependencies to latest -> #379

This are ideas I got right know. Feel free to comment if you want to add/modify/remove any of them.

Also, feel free to participate to this next major. :+1:

**Comment by alexislefebvre** [comment]
Note that there is another roadmap in #332.

**Comment by Soullivaneuh** [comment]
Yeah I saw it later, but not quite the same.

Thanks for linking it. :+1:

**Comment by Jean85** [comment]
I would add supporting Symfony as `^3.0||^4.0` which would help most people with no big problems on our side. If the maintainers are :+1: with this issue, I would ask them to open a branch for this, I would gladly help.

**Comment by Soullivaneuh** [comment]
@Jean85 `^3.4 || ^4.0` is preferable IMHO, we don't have to support EOL version of Symfony on the next major.

**Comment by Jean85** [comment]
I know, but since we're talking about Symfony, we could impact a great deal of upgrade issues, since it will drag any Symfony component with it. I would prefer to bump it upwards from `^3.0` only if needed; due to their nice BC promise we could have no issues with that.

**Comment by Jean85** [comment]
I've opened #359 to start development of this issue. Obviously a lot of tests are failing, but it's a starting point...

Can we add a tool for automatic CS fixing in this roadmap?

**Comment by Soullivaneuh** [comment]
> Can we add a tool for automatic CS fixing in this roadmap?

@Jean85 Funny to ask, I made one recently: https://flintci.io

May we try it? :smile:

**Comment by Jean85** [comment]
Eheh :smile: we should ask @lsmith77 ...
BTW, can you update the checklist, since #365 got merged?

**Comment by lsmith77** [comment]
I like automation and I do not have any strong preferences .. I used https://styleci.io in the past and liked it. but I am fine trying out something new.

**Comment by Soullivaneuh** [comment]
@lsmith77 The only lack of StyleCI for me is the absence of cli fix possibilities. This is why I made a bridge but this one is not compatible with php-cs-fixer v2 anymore. I'll try a PR for that. :+1: 

> BTW, can you update the checklist, since #365 got merged?

@Jean85 Sorry but I don't see which point this PR solve. :confused:

**Comment by alexislefebvre** [comment]
I think that the biggest challenge will be the compatibility with Alice, work has begun in #297 and #337 and I have no idea about a solution. Help is welcome!

**Comment by Jean85** [comment]
Before solving those, IMHO we should get the build to green in #366, so we can define the range of deps that we want/are able to support... 

@Soullivaneuh, @alexislefebvre are you able to help me?

**Comment by alexislefebvre** [comment]
I think that we should add a note about the 2.x and master in order to explain that new features should go to 2.x. And that this version is still under development.

[nelmio/alice](https://github.com/nelmio/alice) use something like this:

> 2.x is in maintenance mode: PRs are accepted, but no active development is done on it by the maintainers any longer.

We'll also need to explain all the BC changes in order to ease the upgrade to 2.x.

**Comment by Soullivaneuh** [comment]
This issue is completed.
