### ISSUE TITLE
Summary of Symfony 4.0 support

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#353]
It's only a list of issues and PRs related to Symfony 4.0:

- [x] Travis: Support Symfony 3.4 and test PHP 7.2 #351
- [x] Symfony 3.4/4.0 support : KERNEL_DIR is replaced by KERNEL_CLASS #343 
- [x] improve Symfony 4 compatibility #352
- [x] new fixtures loading system: https://github.com/liip/LiipFunctionalTestBundle/pull/346#issuecomment-349081379

Feel free to discuss about problems and solution about the Symfony 4.0 support.

**Comment by lsmith77** [comment]
one of the common issues when doing functional tests with Symfony 4 is that services are now private by default. it might make sense to give some easy way to make a kernel instance forcing specific services to be public.

**Comment by lsmith77** [comment]
we should probably also drop the html5 validation https://github.com/liip/LiipFunctionalTestBundle/issues/251

**Comment by Jean85** [comment]
To access private services, the suggested way is to add a public alias to them, so you don't alter the DI definition with the test, just add a side-access to the instances.

In my tests, I define a `getService($id)` method that adds a `.public_alias` suffix to all my calls, and pre-declare them for all the container; since this bundle caches the container, it's not so heavy to do.

**Comment by lsmith77** [comment]
Yeah that “alias” hack however means we either need to use a different name as you point out .. or we have to rename the original service. imho both are not ideal.

**Comment by alexislefebvre** [comment]
> we should probably also drop the html5 validation #251

I agree.

I try to keep track of the issues related to the next major release in the 2.0 milestone: https://github.com/liip/LiipFunctionalTestBundle/milestone/1

**Comment by Jean85** [comment]
> Yeah that “alias” hack however means we either need to use a different name as you point out .. or we have to rename the original service. imho both are not ideal.

IMHO using my hack is the lesser evil, since it will not alter the app DI configuration. Tests shouldn't alter the SUT.

**Comment by lsmith77** [comment]
I agree in so much as adding an alias is less invasive, however it is still a change to the system. As such the key aspect I see is that such changes can be done on the basis of a single test case, rather than hardcoding it into the functional test kernel for all tests.

**Comment by Jean85** [comment]
Something like a whitelist of services to be rendered public through the public alias?
This would invalidate the whole kernel caching mechanism.

**Comment by lsmith77** [comment]
actually we could do something else entirely. we could define a public service which then gets a list of services injected which one can then fetch. this way we would not have to make the services public or define an alias but still get access to them as if they would be public.

**Comment by BPScott** [comment]
Hi @lsmith77 / @alexislefebvre: If I wanted to to assist in improving support for Symfony 3.4 / 4.0 to which branch should make my changes?

It sounds like the plan is to have two versions of the Bundle:
* v1 development  to target Symfony 2.7 and 3.4 (being on Symfony 3.4 with this bundle version there will be deprecation notices, but that is acceptable)
* v2 development to target Symfony 3.4 and 4.x (being on Symfony 3.4 with this bundler version there can't be any deprecation notices otherwise things won't work with Symfony 4.0)

I'm assuming you want to leave v1 pretty much as it is and focus on v2 development. Should I make PRs to the master branch for v2 development (and there be a v1 branch hanging around somewhere for hotfixes) or shall there be a dedicated v2 branch somewhere?

**Comment by lsmith77** [comment]
fundamentally the question is how we want to deal with the currently open PRs pointing to master. do we even want to consider them for 1.x? if not then we might as well create a 1.x branch.

however I also envision 2.x to get quite a lot of refactoring as we aim split up the base class, so generally maybe current open PRs will not really make sense for anything but 1.x anyway in which case it might make more sense to create a 2.x branch

**Comment by lsmith77** [comment]
we can potentially drop paratest in favor of paraunit https://twitter.com/AlessandroLai/status/952578429483999233

**Comment by alexislefebvre** [comment]
I used fastest personally, we already have a documentation in order to use
it :wink:

Le 15 janv. 2018 13:37, "Lukas Kahwe Smith" <notifications@github.com> a
écrit :

**Comment by lsmith77** [comment]
as long as we don't need to integrate with this Bundle with code, yeah we can document different options. but this solves the fact that paratest is currently unmaintained and not Symfony 4 compatible (see https://github.com/brianium/paratest/pull/290)

**Comment by Jean85** [comment]
> as long as we don't need to integrate with this Bundle with code, yeah we can document different options. but this solves the fact that paratest is currently unmaintained and not Symfony 4 compatible (see brianium/paratest#290)

Exactly, that's why I suggested my project. Paraunit doesn't need any code to be integrated, I just use it together with the Dama/DoctrineTestBundle to achieve DB isolation during concurrent tests execution.

We could do a PR where we drop Paratest in favor of doc explanations about it.

**Comment by Soullivaneuh** [comment]
@lsmith77 @Jean85 We have some dependencies not support Symfony 4.0.

I removed them from `require-dev` and add a special test case for them: https://github.com/liip/LiipFunctionalTestBundle/pull/379/files#diff-354f30a63fb0907d4ad57269548329e3R27

So we can now both support not up to date packages and Symfony 4! :+1:

**Comment by Jean85** [comment]
Great move!! :+1: 
Do we need to put in place any other stuff? Basically, I would like that any error due to a missing package throws an exception with an explicit error message, so it would be clear to the end user that he/she needs to require manually those packages that we couldn't include in the `require` section.

**Comment by alexislefebvre** [comment]
Everything has been fixed in #379, we can now focus on other changes: using traits instead of one big class, documentation, etc.

Should we create a `1.x` branch for the legacy version and merge `2.x` in `master`? We don't need to do this today, maybe we could do this after the first alpha release?

**Comment by Soullivaneuh** [comment]
> I would like that any error due to a missing package throws an exception with an explicit error message

@Jean85 Already done for some packages: https://github.com/liip/LiipFunctionalTestBundle/blob/d028d2af57adb049c84927f3a41d79557cc8c279/Test/WebTestCase.php#L549

You may also consider using this: https://packagist.org/packages/ocramius/package-versions

> Should we create a 1.x branch for the legacy version and merge 2.x in master?

Yes please! It's more common to have `master` for unstable dev.

**Comment by alexislefebvre** [comment]
Let's discuss about the future major release in #381.
