### ISSUE TITLE
Discussion about 2.0 release

### ISSUE THREAD

**Issue by alexislefebvre** [liip/LiipFunctionalTestBundle#381]
Thanks to contributors, a lot of changes have been done in order to prepare a new 2.0 release that will be compatible with Symfony 3.4 and 4.0. #379 was the final step of our initial plan for this new release.

We can now discuss of the remaining changes:

- [x] Documentation: BC changes, guide to migrate to `2.x` branch, etc. #382
- [x] Using traits instead of one big class (the big `WebTestCase`), see https://github.com/liip/LiipFunctionalTestBundle/issues/332#issuecomment-329958638 and https://github.com/liip/LiipFunctionalTestBundle/issues/332#issuecomment-333408870 (I'll try to do it soon but feel free to try by yourself), see #392 and now #398
- [x] Introduce changes that break BC before we release the 2.0 version, all changes that will come after this release will have to respect BC, otherwise they will have to go the next major release
- [ ] Create a 1.x branch for the legacy version and merge 2.x in master? We don't need to do this today, maybe we could do this after the first alpha release?
- [x] Release the `2.0.0-alpha1` version?
- [x] Add a `doc` directory and reduce length of `README.md` ? (see https://github.com/EasyCorp/easy-deploy-bundle#documentation or https://github.com/lexik/LexikFormFilterBundle/blob/master/Resources/doc/index.md for examples)
- [x] Check that examples are up-to-date: https://github.com/liip/LiipFunctionalTestBundle/tree/2.x/ExampleTests, see #457
- [x] Clean the `suggest` part in `composer.json`: outdated reference to Symfony 2.5 and paratest that doesn't work anymore IIRC, see #407
- [x]  [2.0] Cannot load dependent fixtures that needs dependency injection #411 → #432 

Opened Issues and PRs:
- [ ] Make classes final? #380

Changes from `1.x` that can be ported to `2.x`:

- [x] Allow static assertion calls #445
- [x] Use a session name by default #444 (we need to check it it's applicable to Symfony 3 and 4)

Please add any idea you can think of.

**Comment by Soullivaneuh** [comment]
> Using traits instead of one big class

As I said in https://github.com/liip/LiipFunctionalTestBundle/issues/332#issuecomment-354095116, I :+1: this! Maybe opening a dedicated issue about that rather than a comment?

> Create a 1.x branch for the legacy version and merge 2.x in master? We don't need to do this today, maybe we could do this after the first alpha release?

There are several way to go. Sonata case: Master is for not released next major, then we have branches per major version (and the higher is the maintained one).

> Release the 2.0.0-alpha1 version?

Would be a great idea and should be done right now IMHO, because we currently don't have any release supporting Symfony 4 that is already stable from a while now.

Plus, an alpha release still **allows** to introduce BC break changes, so it won't be a problem for the rest of the work to do.

**Comment by alexislefebvre** [comment]
I tried to split `WebTestCase` in several traits and I discovered that traits can't extend a class So some necessary calls to `Symfony\Bundle\FrameworkBundle\Test\WebTestCase` are broken. I'll investigate further.

**Comment by Jean85** [comment]
I'm personally against traits. They are simple a dirty way to avoid copy and paste, and I don't think we have many places were we should use it.

Can we investigate in a case-by-case basis? I don't know many of them, and IMHO some features that we are thinking about splitting in traits could be dropped (see Paratest which is no longer mantained and shouldn't need code integration on our side) or forked in a separate class/lib/bundle.

For the 1.x branch, it should be created from the latest 1.x tag just after the 2.x branch gets merged into master, along with a README change that explains the maintaners' position (we only patch 1.x, 2.x/master for new features).

**Comment by Jean85** [comment]
I started the docs part with #382

**Comment by alexislefebvre** [comment]
Thanks again @Jean85 and @Soullivaneuh, here is the alpha release with your work: https://github.com/liip/LiipFunctionalTestBundle/releases/tag/2.0.0-alpha1

**Comment by alexislefebvre** [comment]
I tested the `2.0.0-alpha1` on a fresh Symfony 4 project and it worked perfectly. ✅

**Comment by Jean85** [comment]
Next week I hope to have time to test this on a project with Symfony 3.4 which currently uses the 1.x release.

**Comment by Soullivaneuh** [comment]
@alexislefebvre Same thing here, works like a charm! :-)

**Comment by enekochan** [comment]
I've tested the 2.0.0-alpha4 in a Symfony 3.4 project (I'm currently updating the production app from Symfony 3.3) and after following the [upgrade guide](https://github.com/liip/LiipFunctionalTestBundle/blob/2.x/UPGRADE-2.0.md) everything worked perfectly :) I'm using cached SQLite and PHPUnit 6.5.8 by the way.

**Comment by alexislefebvre** [comment]
Hello, I think that we should plan a beta release and a final release in September. Do everyone agree? I think that we won't introduce BC break changes on the 2.x branch.

**Comment by wietsewarendorff** [comment]
Hi @alexislefebvre , any news on a release date for 2.0? Milestone was due in february, and the comment above mentiones september. I can see there are still some open issues, but also very little progress.

No rush, just looking forward to it since I have to upgrade to phpunit 7 for my current project (and therefore need it) :)

**Comment by alexislefebvre** [comment]
Tests are broken as of today because of a bug in last releases of Symfony: https://github.com/liip/LiipFunctionalTestBundle/pull/447#issuecomment-421824452

I would like to publish a beta release once this bug will be fixed (nobody complained about my previous comment so they probably agree).

**Comment by alexislefebvre** [comment]
Tests were still broken after the last release of Symfony (3.4.16), it looks like there's an issue with PHPCR, I removed PHPCR and opened a PR in order to discuss about the removal: https://github.com/liip/LiipFunctionalTestBundle/pull/452

**Comment by rvanlaak** [comment]
As you stated in #452, no need to remove PHPCR as tests are green again. Maybe we can continue discussing the release of v2.0?

**Comment by alexislefebvre** [comment]
I think that we'll publish a beta once we'll have found a workaround for #423.

I don't see anything right now that block a beta and a stable release.

**Comment by alexislefebvre** [comment]
I would to fix these issues before releasing a final version:

- [ ] Fails to connect into mysql database when database not created #470
- [ ] Backup is wrong #415

Bonus:

- [ ] Conflict with dama/doctrine-test-bundle #423

**Comment by alexislefebvre** [comment]
Thanks everybody for your help.

I'm closing this in favor of #496
